CREATE TABLE APPLICATION_HISTORY (
    ID INT PRIMARY KEY,
    VERSION VARCHAR(100) NOT NULL,
    APPLIED_DATE TIMESTAMP NULL,
    CONTEXT VARCHAR (10) NULL
);

CREATE TABLE CAR ( 
   ID INT AUTO_INCREMENT PRIMARY KEY,
   ID_DEALER INT NOT NULL,
   CODE VARCHAR(50) NOT NULL,   
   CAR_MAKE VARCHAR(50) NOT NULL,
   MODEL VARCHAR(50) NOT NULL,
   KW INT NOT NULL,
   CAR_YEAR INT NOT NULL,
   COLOR VARCHAR(50) NOT NULL,
   PRICE DECIMAL(12, 2) NOT NULL
);

CREATE TABLE DEALER ( 
   ID INT NOT NULL PRIMARY KEY
);

